config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
    root 'bulletins#index'

    namespace :admin do
      resource :session, only: %i[new create]

      resources :bulletins, only: %i[index destroy] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end

      resources :categories, only: %i[index new create edit update destroy]
      resources :users, only: %i[index edit update destroy]
    end

    resources :bulletins, only: %i[index show new create edit update] do
      scope module: :bulletins do
        resources :contacts, only: :create
      end

      member do
        patch :moderate
        patch :archive
        patch :draft
      end
    end

    resource :profile, only: :show

    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    delete 'auth/sign_out', to: 'auth#destroy', as: :sign_out
  end
end

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  #flashMessage.container.my-2
    - flash.each do |type, msg|
      .alert.alert-dismissible.fade.show class="alert-#{type == 'notice' ? 'success' : 'danger'}"
        = msg
        = button_tag('', type: 'button', class: 'btn-close', data: { 'bs-dismiss' => 'alert' })

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-expand-md.navbar-dark.navbar-static-top.bg-dark
  .container-fluid
    = link_to(root_path, class: 'navbar-brand') do
      .d-flex
        i.fa-solid.fa-bullhorn.fa-2x
        span.align-self-center.ms-2 = t('.brand')
    = button_tag(class: 'navbar-toggler', type: 'button',
            data: { 'bs-toggle' => 'collapse', 'bs-target' => '#navbarSupportedContent' },
            aria: { expanded: 'false', controls: 'navbarSupportedContent', label: 'Toggle navigation' }) do
      = content_tag(:span, '', class: 'navbar-toggler-icon')

    #navbarSupportedContent.collapse.navbar-collapse.flex-row-reverse
      ul.navbar-nav
        - if user_signed_in?
          - if user_admin?
            li.nav-item.dropdown
              = link_to(t('.admin'), '#', class: 'nav-link active dropdown-toggle', id: 'adminDropdownMenuLink',
                      data: { 'bs-toggle' => 'dropdown' }, aria: { expanded: 'false' }, role: :button)
              ul.dropdown-menu.dropdown-menu-dark[aria-labelledby="adminDropdownMenuLink"]
                li = link_to(t('.bulletins'), admin_bulletins_path, class: 'dropdown-item')
                li = link_to(t('.categories'), admin_categories_path, class: 'dropdown-item')
                li = link_to(t('.users'), admin_users_path, class: 'dropdown-item')

          li.nav-item.dropdown
            = link_to(current_user.email, '#', class: 'nav-link active dropdown-toggle', id: 'userDropdownMenuLink',
                    data: { 'bs-toggle' => 'dropdown' }, aria: { expanded: 'false' }, role: :button)
            ul.dropdown-menu.dropdown-menu-dark[aria-labelledby="userDropdownMenuLink"]
              li = link_to(t('.my_bulletins'), profile_path, class: 'dropdown-item')
              li = link_to(t('.sign_out'), sign_out_path, method: :delete, class: 'dropdown-item')
        - else
          li.nav-item.dropdown
            = link_to(t('.authentication'), '#', class: 'nav-link active dropdown-toggle', id: 'userDropdownMenuLink',
                    data: { 'bs-toggle' => 'dropdown' }, aria: { expanded: 'false' }, role: :button)
            ul.dropdown-menu.dropdown-menu-dark[aria-labelledby="userDropdownMenuLink"]
              li = link_to('Github', auth_request_path('github'), method: :post, class: 'dropdown-item')
              li = link_to('Google', auth_request_path('google_oauth2'), method: :post, class: 'dropdown-item')