config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
    root 'bulletins#index'

    namespace :admin do
      resource :session, only: %i[new create]

      resources :bulletins, only: %i[index destroy] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end

      resources :categories, only: %i[index new create edit update destroy]
      resources :users, only: %i[index edit update destroy]
    end

    resources :bulletins, only: %i[index show new create edit update] do
      scope module: :bulletins do
        resources :contacts, only: :create
      end

      member do
        patch :moderate
        patch :archive
        patch :draft
      end
    end

    resource :profile, only: :show

    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    delete 'auth/sign_out', to: 'auth#destroy', as: :sign_out
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  aasm whiny_transitions: false, column: :state do
    state :draft, initial: true
    state :under_moderation, :published, :rejected, :archived

    event :moderate do
      transitions from: %i[draft rejected], to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation published rejected], to: :archived
    end

    event :to_draft do
      transitions from: :published, to: :draft
    end
  end

  belongs_to :user
  belongs_to :category
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image, attached: true, content_type: %i[png jpg jpeg], size: { less_than_or_equal_to: 5.megabytes }
end

app/models/bulletins/contact.rb
# frozen_string_literal: true

module Bulletins
  class Contact < MailForm::Base
    attribute :name, validate: true
    attribute :email, validate: :correct_email?
    attribute :message, validate: true
    attribute :bulletin_id, validate: :correct_bulletin_id?

    attr_reader :bulletin, :owner_email

    def bulletin_id=(value)
      refresh_owner_email(refresh_bulletin_obj(value))
      @bulletin_id = value
    end

    def headers
      {
        template_name: 'bulletins/contact',
        subject: I18n.t('mail_form.bulletins.contact.subject'),
        from: %("#{name}" <#{email}>),
        to: owner_email
      }
    end

    def markdown_message
      options = %i[
        hard_wrap autolink no_intra_emphasis tables fenced_code_blocks
        disable_indented_code_blocks strikethrough lax_spacing space_after_headers
        quote footnotes highlight underline
      ]

      Markdown.new(message, *options).to_html
    end

    private

    def correct_email?
      return if email.present? && email.match?(URI::MailTo::EMAIL_REGEXP) && email != owner_email

      errors.add(:email, email.blank? ? :blank : :invalid)
    end

    def correct_bulletin_id?
      return if bulletin.present?

      errors.add(:bulletin_id, :invalid)
    end

    def refresh_bulletin_obj(bulletin_id)
      @bulletin = Bulletin.find_by(id: bulletin_id)
    end

    def refresh_owner_email(bulletin)
      @owner_email = bulletin.present? ? bulletin.user.email : nil
    end
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class BulletinsController < ApplicationController
      def index
        @search = Bulletin.includes(:user, :category).order(created_at: :desc).ransack(params[:q])
        @bulletins = @search.result.page(params[:page])
      end

      def destroy
        bulletin.destroy!
        redirect_to(admin_bulletins_path, notice: t('.success'))
      end

      def publish
        flash_message = bulletin.publish! ? { notice: t('.success') } : { alert: t('.failure') }
        redirect_to(admin_bulletins_path, flash_message)
      end

      def reject
        flash_message = bulletin.reject! ? { notice: t('.success') } : { alert: t('.failure') }
        redirect_to(admin_bulletins_path, flash_message)
      end

      def archive
        flash_message = bulletin.archive! ? { notice: t('.success') } : { alert: t('.failure') }
        redirect_to(admin_bulletins_path, flash_message)
      end

      private

      def bulletin
        @bulletin ||= Bulletin.find(params[:id])
      end
    end
  end
end

app/controllers/web/bulletins/contacts_controller.rb
# frozen_string_literal: true

module Web
  module Bulletins
    class ContactsController < ApplicationController
      invisible_captcha only: :create

      def create
        @contact = ::Bulletins::Contact.new(contact_params)
        authorize(@contact)

        if @contact.deliver
          redirect_to(@contact.bulletin, notice: t('.success'))
        else
          redirect_to(@contact.bulletin, alert: t('.failure'))
        end
      end

      private

      def contact_params
        params.require(:bulletins_contact).permit(:name, :email, :message, :bulletin_id)
      end
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

module Web
  class BulletinsController < ApplicationController
    def index
      @search = Bulletin.includes(:category, image_attachment: :blob).published.ransack(params[:q])
      @bulletins = @search.result.order(created_at: :desc).page(params[:page]).per(12)
    end

    def show
      authorize(bulletin)
    end

    def new
      authorize(Bulletin)
      @bulletin = Bulletin.new
    end

    def edit
      authorize(bulletin)
    end

    def create
      authorize(Bulletin)
      @bulletin = current_user.bulletins.build(bulletin_params)

      if @bulletin.save
        redirect_to(@bulletin, notice: t('.success'))
      else
        flash.now.alert = t('.failure')
        render(:new, status: :unprocessable_entity)
      end
    end

    def update
      authorize(bulletin)

      if bulletin.update(bulletin_params)
        redirect_to(bulletin, notice: t('.success'))
      else
        flash.now.alert = t('.failure')
        render(:edit, status: :unprocessable_entity)
      end
    end

    def moderate
      authorize(bulletin)
      flash_message = bulletin.moderate! ? { notice: t('.success') } : { alert: t('.failure') }
      redirect_to(profile_path, flash_message)
    end

    def archive
      authorize(bulletin)
      flash_message = bulletin.archive! ? { notice: t('.success') } : { alert: t('.failure') }
      redirect_to(profile_path, flash_message)
    end

    def draft
      authorize(bulletin)
      flash_message = bulletin.to_draft! ? { notice: t('.success') } : { alert: t('.failure') }
      redirect_to(profile_path, flash_message)
    end

    private

    def bulletin
      @bulletin ||= Bulletin.find(params[:id])
    end

    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :category_id, :image)
    end
  end
end

app/helpers/bulletins_helper.rb
# frozen_string_literal: true

module BulletinsHelper
end

app/views/web/bulletins/_bulletin_contact_form.html.slim
= simple_form_for(BulletinContact.new, url: bulletin_contacts_path(bulletin)) do |f|
  = invisible_captcha
  = f.input(:bulletin_id, as: :hidden, input_html: { value: bulletin.id })
  = f.input(:name, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' })
  = f.input(:email, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' }, required: true)
  = f.input(:message, as: :text, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' },
          input_html: { rows: 5 }, hint: t('.markdown_support'))
  .d-flex.flex-column
    = f.button(:submit, t('.submit'), class: 'btn-success my-2')
    = button_tag(t('.cancel'), type: 'button', class: 'btn btn-secondary my-2',
            data: { 'bs-toggle' => 'collapse', 'bs-target' => '.bulletin-contact' },
            aria: { expanded: 'false', controls: 'bulletin-contact' })

app/views/web/bulletins/_bulletins_contact_form.html.slim
= simple_form_for(Bulletins::Contact.new, url: bulletin_contacts_path(bulletin)) do |f|
  = invisible_captcha
  = f.input(:bulletin_id, as: :hidden, input_html: { value: bulletin.id })
  = f.input(:name, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' })
  = f.input(:email, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' }, required: true)
  = f.input(:message, as: :text, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' },
          input_html: { rows: 5 }, hint: t('.markdown_support'))
  .d-flex.flex-column
    = f.button(:submit, t('.submit'), class: 'btn-success my-2')
    = button_tag(t('.cancel'), type: 'button', class: 'btn btn-secondary my-2',
            data: { 'bs-toggle' => 'collapse', 'bs-target' => '.bulletins-contact' },
            aria: { expanded: 'false', controls: 'bulletins-contact' })

app/views/web/bulletins/_control_panel.html.slim
.d-flex.flex-column.my-2.collapse.bulletins-contact.show
  - if !user_signed_in? || (bulletin.user != current_user && bulletin.published?)
    .py-2
      = button_tag(t('.bulletin_contact_button'), class: 'btn btn-secondary w-100', type: 'button',
              data: { 'bs-toggle' => 'collapse', 'bs-target' => '.bulletins-contact' },
              aria: { expanded: 'false', controls: 'bulletins-contact' })
  - if user_admin?
    .py-2
      = button_tag(t('.main_control_button'), data: { 'bs-toggle': :dropdown, 'aria-expanded': false },
              type: :button, class: 'btn btn-danger w-100 dropdown-toggle text-wrap')
      ul.dropdown-menu.dropdown-menu-dark
        - if bulletin.user == current_user
          - if bulletin.may_moderate?
            li = link_to(t('.edit_link'), edit_bulletin_path(bulletin), class: 'dropdown-item')
            li = link_to(t('.moderate_link'), moderate_bulletin_path(bulletin), method: :patch,
                    class: 'dropdown-item', data: { confirm: t('.confirm_moderation') })
          - if bulletin.may_to_draft?
            li = link_to(t('.to_draft_link'), draft_bulletin_path(bulletin), method: :patch,
                    class: 'dropdown-item', data: { confirm: t('.confirm_to_draft') })
        li = link_to(t('.destroy_link'), admin_bulletin_path(bulletin), method: :delete,
                class: 'dropdown-item', data: { confirm: t('.confirm_destruction') })
        - if bulletin.may_publish?
          li = link_to(t('.publish_link'), publish_admin_bulletin_path(bulletin), method: :patch,
                  class: 'dropdown-item', data: { confirm: t('.confirm_publication') })
        - if bulletin.may_reject?
          li = link_to(t('.reject_link'), reject_admin_bulletin_path(bulletin), method: :patch,
                  class: 'dropdown-item', data: { confirm: t('.confirm_rejection') })
        - if bulletin.may_archive?
          li = link_to(t('.archive_link'), archive_admin_bulletin_path(bulletin), method: :patch,
                  class: 'dropdown-item', data: { confirm: t('.confirm_archiving') })
    .py-2
      = button_tag(t('.pages_control_button'), data: { 'bs-toggle': :dropdown, 'aria-expanded': false },
              type: :button, class: 'btn btn-primary w-100 dropdown-toggle text-wrap')
      ul.dropdown-menu.dropdown-menu-dark
        li = link_to(t('.admin_bulletins_link'), admin_bulletins_path, class: 'dropdown-item')
        - if bulletin.user == current_user
          li = link_to(t('.my_profile_link'), profile_path, class: 'dropdown-item')
        li = link_to(t('.main_page_link'), bulletins_path, class: 'dropdown-item')
  - elsif user_signed_in? && bulletin.user == current_user
    - if bulletin.may_archive?
      .py-2
        = button_tag(t('.main_control_button'), data: { 'bs-toggle': :dropdown, 'aria-expanded': false },
                type: :button, class: 'btn btn-danger w-100 dropdown-toggle text-wrap')
        ul.dropdown-menu.dropdown-menu-dark
          - if bulletin.may_moderate?
            li = link_to(t('.edit_link'), edit_bulletin_path(bulletin), class: 'dropdown-item')
            li = link_to(t('.moderate_link'), moderate_bulletin_path(bulletin), method: :patch,
                    class: 'dropdown-item', data: { confirm: t('.confirm_moderation') })
          - if bulletin.may_to_draft?
            li = link_to(t('.to_draft_link'), draft_bulletin_path(bulletin), method: :patch,
                    class: 'dropdown-item', data: { confirm: t('.confirm_to_draft') })
          li = link_to(t('.archive_link'), archive_bulletin_path(bulletin), method: :patch,
                  class: 'dropdown-item', data: { confirm: t('.confirm_archiving') })
    .py-2
      = button_tag('Вернуться на страницу', data: { 'bs-toggle': :dropdown, 'aria-expanded': false },
              type: :button, class: 'btn btn-primary w-100 dropdown-toggle text-wrap')
      ul.dropdown-menu.dropdown-menu-dark
        li = link_to(t('.my_profile_link'), profile_path, class: 'dropdown-item')
        li = link_to(t('.main_page_link'), bulletins_path, class: 'dropdown-item')
  - else
    .py-2
      = link_to(t('.main_page_link'), bulletins_path, class: 'btn btn-primary w-100')

app/views/web/bulletins/_form.html.slim
= simple_form_for(bulletin) do |f|
  = f.input(:title, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' })
  = f.input(:description, hint: t('.markdown_support'), wrapper_html: { class: 'my-2' },
          label_html: { class: 'fst-italic' }, input_html: { rows: 5 })
  = f.association(:category, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' },
          input_html: { class: 'form-select' })
  - if bulletin.image.attached?
    = image_tag(bulletin.image.variant(resize_to_limit: [200, 100]), class: 'img-thumbnail mb-2')
  = f.input(:image, wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' },
          input_html: { class: 'form-control', accept: 'image/png,image/jpeg' }, required: true)
  .custom-form-actions
    = f.button(:submit, t('.submit'), class: 'btn-success my-2')
    = link_to(t('.cancel_link'), profile_path, class: 'btn btn-secondary my-2')

app/views/web/bulletins/_search_form.html.slim
= search_form_for(search, url: bulletins_path, method: :get) do |f|
  .row
    .col-lg-4
      = f.input(:title_cont, label: t('.title_cont'), wrapper_html: { class: 'my-2' },
              label_html: { class: 'fst-italic' }, required: false)
    .col-lg-4
      = f.input(:user_name_cont, label: t('.user_name_cont'), wrapper_html: { class: 'my-2' },
              label_html: { class: 'fst-italic' }, required: false)
    .col-lg-4
      = f.input(:category_id_eq, as: :select, label: t('.category_id_eq'), collection: Category.all,
              wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' },
              input_html: { class: 'form-select' }, required: false)
  .custom-form-actions
    = f.button(:submit, t('.submit'), class: 'btn-success my-2')
    = link_to(t('.clear_filter_link'), bulletins_path, class: 'btn btn-danger my-2')

app/views/web/bulletins/edit.html.slim
.container-md.my-4
  h2.mb-4 = t('.main_title')

  .row
    .col-12.col-lg-6
      = render(partial: 'form', locals: { bulletin: @bulletin })

app/views/web/bulletins/index.html.slim
.container-lg.my-4
  .p-4.align-items-center.border.border-2.rounded-3.shadow.bg-white
    .row.g-0
      .p-2
        h2 = t('.main_title')
        hr
        .my-4.p-3.bg-light.border.border-2.rounded-3
          h5.mt-2 = t('.search_form_title')
          = render(partial: 'search_form', locals: { search: @search })
        .row
          - if @bulletins.exists?
            - @bulletins.each do |bulletin|
              .pb-4.col-xl-3.col-lg-4.col-md-6.col-xs-12
                .card.shadow-sm.h-100
                  = image_tag(bulletin.image, class: 'card-img-top', size: 250, style: 'object-fit: cover;')
                  .card-body
                    .d-flex.align-items-start.flex-column.h-100
                      h5.card-title = bulletin.title
                      h6.card-subtitle.mb-4.text-muted = bulletin.category.name
                      = link_to(t('.bulletin_button'), bulletin_path(bulletin), class: 'btn btn-primary w-100 mt-auto')
            .d-flex.justify-content-between.flex-wrap
              = content_tag(:span, page_entries_info(@bulletins), class: 'pt-2 text-nowrap')
              = paginate(@bulletins, window: 2, pagination_class: 'mb-0')
          - else
            = content_tag(:p, page_entries_info(@bulletins))

app/views/web/bulletins/new.html.slim
.container-md.my-4
  h2.mb-4 = t('.main_title')

  .row
    .col-12.col-lg-6
      = render(partial: 'form', locals: { bulletin: @bulletin })

app/views/web/bulletins/show.html.slim
.container-lg.my-4
  .p-4.align-items-center.border.border-2.rounded-3.shadow.bg-white
    .row
      .p-3.p-lg-5.pt-lg-0
        .mb-4
          h2 = @bulletin.title
          hr
        .custom-card
          .row.g-0
            .col-md-6.col-lg-4.p-3
              = image_tag(@bulletin.image, class: 'img-fluid rounded-start')
              = render(partial: 'control_panel', locals: { bulletin: @bulletin })
              .row.g-0.py-2.collapse.bulletins-contact
                .col-12
                  h5.mt-2 = Bulletins::Contact.model_name.human
                  = render(partial: 'bulletins_contact_form', locals: { bulletin: @bulletin })
            .col-md-6.col-lg-8.p-3
              .text-start
                .row
                  .col-md-6
                    h5
                      strong = "#{Bulletin.human_attribute_name(:user)}:"
                      =< @bulletin.user.name
                  .col-md-6
                    h5
                      strong = "#{Bulletin.human_attribute_name(:created_at)}:"
                      =< l(@bulletin.created_at, format: :long)
                  .col-md-6
                    h5
                      strong = "#{Bulletin.human_attribute_name(:category)}:"
                      =< @bulletin.category.name
                  .col-md-6
                    h5
                      strong = "#{Bulletin.human_attribute_name(:updated_at)}:"
                      =< l(@bulletin.updated_at, format: :long)
                  .col-md-6
                    h5
                      strong = "#{Bulletin.human_attribute_name(:state)}:"
                      =< @bulletin.aasm.human_state
                hr
                p == markdown(@bulletin.description)