config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
    root 'bulletins#index'

    namespace :admin do
      resource :session, only: %i[new create]

      resources :bulletins, only: %i[index destroy] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end

      resources :categories, only: %i[index new create edit update destroy]
      resources :users, only: %i[index edit update destroy]
    end

    resources :bulletins, only: %i[index show new create edit update] do
      scope module: :bulletins do
        resources :contacts, only: :create
      end

      member do
        patch :moderate
        patch :archive
        patch :draft
      end
    end

    resource :profile, only: :show

    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    delete 'auth/sign_out', to: 'auth#destroy', as: :sign_out
  end
end

app/controllers/web/profiles_controller.rb
# frozen_string_literal: true

module Web
  class ProfilesController < ApplicationController
    def show
      authorize([:profile, Bulletin])
      @search = current_user.bulletins.includes(:category).order(created_at: :desc).ransack(params[:q])
      @bulletins = @search.result.page(params[:page])
    end
  end
end

app/views/web/profiles/_search_form.html.slim
= search_form_for(search, url: profile_path, method: :get) do |f|
  .row
    .col-lg-4
      = f.input(:title_cont, label: t('.title_cont'), wrapper_html: { class: 'my-2' },
              label_html: { class: 'fst-italic' }, required: false)
    .col-lg-4
      = f.input(:state_eq, as: :select, label: t('.state_eq'),
              collection: Bulletin.aasm.states.map { |state| [state.human_name, state.name] },
              wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' },
              input_html: { class: 'form-select' }, required: false)
    .col-lg-4
      = f.input(:category_id_eq, as: :select, label: t('.category_id_eq'), collection: Category.all,
              wrapper_html: { class: 'my-2' }, label_html: { class: 'fst-italic' },
              input_html: { class: 'form-select' }, required: false)
  .custom-form-actions
    = f.button(:submit, t('.submit'), class: 'btn-success my-2')
    = link_to(t('.clear_filter_link'), profile_path, class: 'btn btn-danger my-2')

app/views/web/profiles/show.html.slim
.container-xl.my-4
  .p-4.align-items-center.border.border-2.rounded-3.shadow.bg-white
    .row.g-0
      .p-2
        h2 = t('.main_title')
        hr
        .my-4.p-3.bg-light.border.border-2.rounded-3
          h5.mt-2 = t('.search_form_title')
          = render(partial: 'search_form', locals: { search: @search })
        - if @bulletins.exists?
          .table-responsive.border.border-2.rounded-3.border-dark.mb-2
            table.table.table-bordered.table-sm.table-hover.border-dark.text-center.align-middle.mb-0
              thead.table-dark.border-dark
                tr
                  th[scope='col'] #
                  th[scope='col'] = Bulletin.human_attribute_name(:title)
                  th[scope='col'] = Bulletin.human_attribute_name(:state)
                  th[scope='col'] = Bulletin.human_attribute_name(:category)
                  th[scope='col'] = t('.actions_table_column')
              tbody.border-dark
                - @bulletins.each.with_index(start_index(@bulletins)) do |bulletin, i|
                  tr.text-wrap
                    th[scope='row'] = i
                    td.text-wrap = bulletin.title
                    td = bulletin.aasm.human_state
                    td = bulletin.category.name
                    td
                      .btn-group
                        = link_to(t('.actions.show_bulletin'), bulletin_path(bulletin),
                                class: 'btn btn-primary btn-sm')
                        - if bulletin.may_archive?
                          = button_tag('', type: :button, data: { 'bs-toggle': :dropdown, 'aria-expanded': false },
                                  class: 'btn btn-sm btn-secondary dropdown-toggle', id: "dropdown-btn-#{i}")
                          ul.dropdown-menu.dropdown-menu-dark id="dropdown-menu-#{i}"
                            - if bulletin.may_moderate?
                              li = link_to(t('.actions.edit_bulletin'), edit_bulletin_path(bulletin),
                                      class: 'dropdown-item')
                              li = link_to(t('.actions.moderate_bulletin'), moderate_bulletin_path(bulletin),
                                      method: :patch, class: 'dropdown-item',
                                      data: { confirm: t('.actions.confirm_moderation') })
                            - if bulletin.may_to_draft?
                              li = link_to(t('.actions.to_draft_bulletin'), draft_bulletin_path(bulletin),
                                      method: :patch, class: 'dropdown-item',
                                      data: { confirm: t('.actions.confirm_to_draft') })
                            li = link_to(t('.actions.archive_bulletin'), archive_bulletin_path(bulletin),
                                    method: :patch, class: 'dropdown-item',
                                    data: { confirm: t('.actions.confirm_archiving') })
              tfoot.table-dark.border-dark
                tr
                  td.border-bottom-0[colspan='5']
                    .d-flex.justify-content-between
                      = content_tag(:span, page_entries_info(@bulletins), class: 'me-2 text-nowrap')
                      = paginate(@bulletins, window: 2, pagination_class: 'pagination-sm mb-0')

        - else
          = content_tag(:p, page_entries_info(@bulletins))

        = link_to(t('.actions.create_bulletin'), new_bulletin_path, class: 'btn btn-primary')